---
# https://docs.python.org/3/library/logging.config.html#logging-config-fileformat

version: 1

formatters:
  long:
    format: "%(levelname)s - %(name)s - %(threadName)s - %(asctime)s - %(filename)s:%(lineno)d: %(message)s"

  short:
    format: "%(levelname)s - %(asctime)s - [%(filename)s:%(lineno)d] %(message)s"

handlers:
  file:
    class: logging.StreamHandler
    formatter: long
    stream: ext://sys.stdout

  stdout:
    class: logging.handlers.RotatingFileHandler
    formatter: short
    filename: logs/log.txt
    maxBytes: 2621444
    backupCount: 3

loggers:
  root:
    handlers: [stdout, file]
    level: NOTSET
    propagate: yes
