---
# See https://github.com/anothrNick/github-tag-action
name: merge-release

on:
  # Runs on pushes to main
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to enable find/replace push
permissions: write-all

jobs:
  merge-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@1
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
