---
# See https://github.com/mathieudutour/github-tag-action
name: merge-release

on:
  # Runs on pushes to main
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@1
        env:
          DEFAULT_BUMP: patch
          DRY_RUN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "version = \".*\""
          replace: "version = \"${{ steps.bump.outputs.tag }}\""
          include: "pyproject.toml"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
