---
# See https://github.com/mathieudutour/github-tag-action
name: pr-release

on:
  # Runs on pushes to main
  pull_request:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to enable find/replace push
permissions: write-all

jobs:
  pr-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@1
        env:
          DEFAULT_BUMP: patch
          DRY_RUN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
      - name: Find and replace version in pyproject.toml and conf.py
        run: |
          sed -i "s/version = \".*\"/version = \"${{ steps.bump.outputs.tag }}\"/g" ./pyproject.toml
          sed -i "s/version = \".*\"/version = \"${{ steps.bump.outputs.tag }}\"/g" ./docsrc/conf.py
      - uses: EndBug/add-and-commit@v9
        with:
          message: ${{ steps.bump.outputs.tag }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
